name: Lodicak
description: Quiz app
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  golden_toolkit: ^0.8.0
  provider: ^4.1.3
  sentry_flutter: ^4.0.4
  auto_size_text: ^2.1.0
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  rflutter_alert: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: ^1.14.4
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/cevni/
    - images/plachty/
    - images/app/

